config/routes.rb
Rails.application.routes.draw do

# Home route
root "pages#home"

#About route
get '/about', to: "pages#about"

#Help route
get '/help', to: "pages#help"

resources :todos
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
validates :name, presence: true
validates :desc, presence: true 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

def home

end

def about

end

def help

end

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

before_action  :set_todo, only: [:edit,:update,:show,:destroy]

def index
@todos = Todo.all
end

  def new
  @todo = Todo.new
  end

  def create
  @todo = Todo.new(todo_params)
    if @todo.save
    flash[:notice] = "Todo was created sucessfully"
    redirect_to todo_path(@todo)
    else
    render 'new'
    end
  end

  def show

  end

  def edit

  end

  def update

    if @todo.update(todo_params)
    flash[:notice] = "Todo was sucessfully upadated"
    redirect_to todo_path(@todo)
    else
      render 'edit'
    end
  end

  def destroy

    @todo.destroy
    flash[:notice] = "Todo was deleted sucessfully"
    redirect_to todos_path
  end

private

  def set_todo
      @todo = Todo.find(params[:id])
  end

  def todo_params
    params.require(:todo).permit(:name, :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flashmessages.html.erb
<% flash.each do |name,msg| %>
<ul>
  <li>
    <%= msg %>
  </li>
</ul>
<% end %>

app/views/layouts/_forms.html.erb
<% if  @todo.errors.any? %>
<h3>The following errors has accorded </h3>
<ul>
<%  @todo.errors.full_messages.each do |msg| %>
  <li> <%= msg  %>
  <% end %>
</ul>
<% end %>
<%= form_for @todo do |f| %>
 <p>
   <%= f.label :name %><br>
   <%= f.text_field :name %>
 </p>
 <p>
   <%= f.label :desc %><br>
   <%= f.text_area :desc %>
 </p>
 <p>
   <%= f.submit %>
 </p>
 <% end %>
 <%= link_to "Back to listing", todos_path %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todoapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


    <h1>Danish Test</h1>

    <%= render 'layouts/flashmessages'%>

    <%= yield %>
  </body>
</html>

app/views/pages/about.erb
<h1>This is About</<h1>

app/views/pages/help.html.erb
<h1>This is helps</h1>

app/views/pages/home.html.erb
<h1>Hello World!</h1>

app/views/todos/edit.html.erb
<h1>Edit an exitsing todo</h1>

<%= render 'layouts/forms' %>

app/views/todos/index.html.erb
<h1> listing all todo</h1>

<p>
 <%= link_to "Creat a Todo", new_todo_path %>
</p>

<table>
<tr>

  <th>Name</th>
  <th>Description</th>
</tr>
<% @todos.each do |todo| %>
<tr>
  <td><%= todo.name %></td>
  <td><%= todo.desc%></td>
  <td><%= link_to "Edit", edit_todo_path(todo) %></td>
  <td><%= link_to "Show", todo_path(todo) %></td>
  <td><%= link_to "Delete", todo_path(todo), method: :delete, data:{confirm: "Are you sure ?"} %></td>
</tr>
<% end %>
</table>

app/views/todos/new.html.erb
<h1>This is new pages</h1>

<% if  @todo.errors.any? %>
<h3>The following errors has accorded </h3>
<ul>
<%  @todo.errors.full_messages.each do |msg| %>
  <li> <%= msg  %>
  <% end %>
</ul>
<% end %>

<%= form_for @todo do |f| %>
 <p>
   <%= f.label :name %><br>
   <%= f.text_field :name %>
 </p>
 <p>
   <%= f.label :desc %><br>
   <%= f.text_area :desc %>
 </p>
 <p>
   <%= f.submit %>
 </p>

<% end %>

<%= link_to "Back to listing", todos_path %> 

app/views/todos/show.html.erb
<h1> Showing the todo</h1>
<p>
Name: <%= @todo.name%>
</p>
<p>
Description: <%= @todo.desc%>
</p>

<td><%= link_to "Edit this todo", edit_todo_path(@todo) %></td>
<td><%= link_to "Back to listing", todos_path %></td>